# Generated by Django 4.0.6 on 2022-07-23 19:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
